# Generated by Django 4.2.27 on 2026-01-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Cybersecurity', 'Cybersecurity'), ('IT Seminar', 'IT Seminar'), ('Web Development', 'Web Development'), ('Data Science', 'Data Science')], default='IT Seminar', max_length=50),
        ),
    ]
